<?php
return [
    'options' => [
        'API_KEY' => 12345,
        'PIZZAS'=>6,
        'ESPECIALIDADES'=>1,
        'CONTIENE_PIZZA'=>1,
        '2X1_BASICO'=>2,
        '2X1_ESPECIALIDAD'=>3,
        'PAQUETE_VARIOS_PRODUCTOS'=>1,
        'ENTRADAS'=>2,
        'POSTRES'=>3,
        'PAQUETES'=>7,
        'PAQUETES_LEALTAD'=>15,
        'VIGENTE'=>1,
        'PORCIENTO_IMPUESTO_PRODUCTO'=>16,
        'ID_MOSTRADOR'=>1,
        'ID_REPARTO'=>2,
        'STATUS_SIN_GARANTIA'=>1,
        'STATUS_CON_GARANTIA'=>2,
        'ESQUEMACOBRO_DESCUENTO_PEDIDO_EN_LINEA'=>592,
        'ESQUEMACOBRO_APP_PIZZA_GRATIS'=>592,
        'BEBIDAS'=>4,
        'RECETA_BARBECUE'=>81,
        'RECETA_SAPRE'=>28,
        'RECETA_QUESO'=>31,
        'PRODUCTOS_VARIOS'=>1,
        'ARMADO_4X4_BASICO'=>4,
        'ARMADO_4X4_ESPECIALIDAD'=>5,
        '2X1_BASICO'=>2,
        'BAGUETTES'=>5,   
        'PIZZA_BASE'=>36,
        'PIZZA_BASE_ESP'=>37,
        'EXTRA_CHESSE'=>21,
        'RECETA_QUESO_DESLACTOSADO'=>442,
        'RECETA_AJOJOLI'=>16,
        'RECETA_AJOJOLI_NEGRO'=>713,
        'RECETA_ORILLA_QUESO'=>82,
        'RECETA_PAN_CRUJI'=>53,
        'CON_ORILLA'=>1,
        'CON_PANCRUJI'=>1,
        'SIN_ORILLAQUESO'=>1,
        'SIN_PANCRUJI'=>1,  
        'ORILLA_RELLENA_QUESO'=>45,
        'DESCUENTO_DIVIDIDO_ENTRE_PRODUCTOS'=>7,
        'PAGO_CON_AYDEN'=>4,
        'PAGO_CON_REGALA_PIZZA'=>5,
        'IP_API_BACKEND'=>'201.155.236.67',
        'UNIDAD_MENU_REPARTO'=>10,
        'UNIDAD_MENU_SEVILLA'=>10,
        // 'IP_API_BACKEND'=>'127.0.0.1'
        'DESCUENTO_POR_PORCENTAJE'=>2,
        'DESCUENTO_POR_CANTIDAD'=>1,
        'CODIGO_GENERICO'=>1,
        'CODIGO_POR_CLIENTE'=>2,
       
        
    ]
];

?>